eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8761/eureka/  注册到集群eureka当中
#  instance:
#    hostname: projectName   自定义的链接，不一定用到
spring:
  application:
    name: project
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
server:
  port: 8090
mybatis:
  type-aliases-package: com.imooc.project.model
  mapper-locations: classpath:mapper/*.xml
